/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AggregateStorageSummary = IDL.Record({
  'totalPhotosSize' : IDL.Nat,
  'totalVideosSize' : IDL.Nat,
  'totalVideos' : IDL.Nat,
  'totalMemoriesSize' : IDL.Nat,
  'totalPhotos' : IDL.Nat,
  'totalMemories' : IDL.Nat,
  'totalDocumentsSize' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const PhotoMetadata = IDL.Record({
  'id' : IDL.Nat,
  'storageReference' : ExternalBlob,
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
  'uploadDate' : Time,
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'pin' : IDL.Text,
  'languagePreference' : Language,
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const StorageSummary = IDL.Record({
  'videosCount' : IDL.Nat,
  'photosSize' : IDL.Nat,
  'memoriesSize' : IDL.Nat,
  'memoriesCount' : IDL.Nat,
  'documentsSize' : IDL.Nat,
  'videosSize' : IDL.Nat,
  'photosCount' : IDL.Nat,
  'documentsCount' : IDL.Nat,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Nat,
  'storageReference' : ExternalBlob,
  'duration' : IDL.Opt(IDL.Nat),
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'thumbnailReference' : IDL.Opt(ExternalBlob),
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
  'uploadDate' : Time,
});
export const VideosResponse = IDL.Record({
  'message' : IDL.Text,
  'videos' : IDL.Vec(VideoMetadata),
});
export const PhotoUploadRequest = IDL.Record({
  'storageReference' : ExternalBlob,
  'contentType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
});
export const BulkPhotoUploadRequest = IDL.Record({
  'photos' : IDL.Vec(PhotoUploadRequest),
});
export const VideoUploadRequest = IDL.Record({
  'storageReference' : ExternalBlob,
  'duration' : IDL.Opt(IDL.Nat),
  'contentType' : IDL.Text,
  'thumbnailReference' : IDL.Opt(ExternalBlob),
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
});
export const BulkVideoUploadResponse = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'successCount' : IDL.Nat,
  'message' : IDL.Text,
  'videoIds' : IDL.Vec(IDL.Nat),
});
export const VideoUploadResponse = IDL.Record({
  'message' : IDL.Text,
  'videoId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'message' : IDL.Text })],
      [],
    ),
  'downloadVideo' : IDL.Func([IDL.Nat], [], []),
  'getAggregateStorageSummary' : IDL.Func(
      [],
      [AggregateStorageSummary],
      ['query'],
    ),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhotoMetadata' : IDL.Func([IDL.Nat], [PhotoMetadata], ['query']),
  'getPhotoStorageUsage' : IDL.Func([], [IDL.Nat], ['query']),
  'getUniqueUserProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserLanguagePreference' : IDL.Func([], [Language], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStorageSummary' : IDL.Func(
      [IDL.Principal],
      [StorageSummary],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Nat], [VideoMetadata], ['query']),
  'getVideoStorageUsage' : IDL.Func([], [IDL.Nat], ['query']),
  'getVideos' : IDL.Func([], [VideosResponse], ['query']),
  'getVirtualCanisterCount' : IDL.Func([], [IDL.Nat], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetPin' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserLanguagePreference' : IDL.Func([Language], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'uploadMultiplePhotos' : IDL.Func(
      [BulkPhotoUploadRequest],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'uploadMultipleVideos' : IDL.Func(
      [IDL.Record({ 'videos' : IDL.Vec(VideoUploadRequest) })],
      [BulkVideoUploadResponse],
      [],
    ),
  'uploadPhoto' : IDL.Func([PhotoUploadRequest], [IDL.Nat], []),
  'uploadVideo' : IDL.Func([VideoUploadRequest], [VideoUploadResponse], []),
  'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AggregateStorageSummary = IDL.Record({
    'totalPhotosSize' : IDL.Nat,
    'totalVideosSize' : IDL.Nat,
    'totalVideos' : IDL.Nat,
    'totalMemoriesSize' : IDL.Nat,
    'totalPhotos' : IDL.Nat,
    'totalMemories' : IDL.Nat,
    'totalDocumentsSize' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const PhotoMetadata = IDL.Record({
    'id' : IDL.Nat,
    'storageReference' : ExternalBlob,
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
    'uploadDate' : Time,
  });
  const Language = IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null });
  const UserProfile = IDL.Record({
    'pin' : IDL.Text,
    'languagePreference' : Language,
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const StorageSummary = IDL.Record({
    'videosCount' : IDL.Nat,
    'photosSize' : IDL.Nat,
    'memoriesSize' : IDL.Nat,
    'memoriesCount' : IDL.Nat,
    'documentsSize' : IDL.Nat,
    'videosSize' : IDL.Nat,
    'photosCount' : IDL.Nat,
    'documentsCount' : IDL.Nat,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Nat,
    'storageReference' : ExternalBlob,
    'duration' : IDL.Opt(IDL.Nat),
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'thumbnailReference' : IDL.Opt(ExternalBlob),
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
    'uploadDate' : Time,
  });
  const VideosResponse = IDL.Record({
    'message' : IDL.Text,
    'videos' : IDL.Vec(VideoMetadata),
  });
  const PhotoUploadRequest = IDL.Record({
    'storageReference' : ExternalBlob,
    'contentType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const BulkPhotoUploadRequest = IDL.Record({
    'photos' : IDL.Vec(PhotoUploadRequest),
  });
  const VideoUploadRequest = IDL.Record({
    'storageReference' : ExternalBlob,
    'duration' : IDL.Opt(IDL.Nat),
    'contentType' : IDL.Text,
    'thumbnailReference' : IDL.Opt(ExternalBlob),
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const BulkVideoUploadResponse = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'successCount' : IDL.Nat,
    'message' : IDL.Text,
    'videoIds' : IDL.Vec(IDL.Nat),
  });
  const VideoUploadResponse = IDL.Record({
    'message' : IDL.Text,
    'videoId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'message' : IDL.Text })],
        [],
      ),
    'downloadVideo' : IDL.Func([IDL.Nat], [], []),
    'getAggregateStorageSummary' : IDL.Func(
        [],
        [AggregateStorageSummary],
        ['query'],
      ),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhotoMetadata' : IDL.Func([IDL.Nat], [PhotoMetadata], ['query']),
    'getPhotoStorageUsage' : IDL.Func([], [IDL.Nat], ['query']),
    'getUniqueUserProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserLanguagePreference' : IDL.Func([], [Language], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStorageSummary' : IDL.Func(
        [IDL.Principal],
        [StorageSummary],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Nat], [VideoMetadata], ['query']),
    'getVideoStorageUsage' : IDL.Func([], [IDL.Nat], ['query']),
    'getVideos' : IDL.Func([], [VideosResponse], ['query']),
    'getVirtualCanisterCount' : IDL.Func([], [IDL.Nat], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetPin' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserLanguagePreference' : IDL.Func([Language], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'uploadMultiplePhotos' : IDL.Func(
        [BulkPhotoUploadRequest],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'uploadMultipleVideos' : IDL.Func(
        [IDL.Record({ 'videos' : IDL.Vec(VideoUploadRequest) })],
        [BulkVideoUploadResponse],
        [],
      ),
    'uploadPhoto' : IDL.Func([PhotoUploadRequest], [IDL.Nat], []),
    'uploadVideo' : IDL.Func([VideoUploadRequest], [VideoUploadResponse], []),
    'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };