/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkPhotoUploadRequest { 'photos' : Array<PhotoUploadRequest> }
export interface BulkVideoUploadResponse {
  'errors' : Array<string>,
  'successCount' : bigint,
  'message' : string,
  'videoIds' : Array<bigint>,
}
export type ExternalBlob = Uint8Array;
export type Language = { 'hindi' : null } |
  { 'english' : null };
export interface PhotoMetadata {
  'id' : bigint,
  'storageReference' : ExternalBlob,
  'contentType' : string,
  'owner' : Principal,
  'fileSize' : bigint,
  'filename' : string,
  'uploadDate' : Time,
}
export interface PhotoUploadRequest {
  'storageReference' : ExternalBlob,
  'contentType' : string,
  'fileSize' : bigint,
  'filename' : string,
}
export type Time = bigint;
export interface UserProfile {
  'pin' : string,
  'languagePreference' : Language,
  'name' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'id' : bigint,
  'storageReference' : ExternalBlob,
  'duration' : [] | [bigint],
  'contentType' : string,
  'owner' : Principal,
  'thumbnailReference' : [] | [ExternalBlob],
  'fileSize' : bigint,
  'filename' : string,
  'uploadDate' : Time,
}
export interface VideoUploadRequest {
  'storageReference' : ExternalBlob,
  'duration' : [] | [bigint],
  'contentType' : string,
  'thumbnailReference' : [] | [ExternalBlob],
  'fileSize' : bigint,
  'filename' : string,
}
export interface VideoUploadResponse { 'message' : string, 'videoId' : bigint }
export interface VideosResponse {
  'message' : string,
  'videos' : Array<VideoMetadata>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePin' : ActorMethod<[string, string], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], { 'message' : string }>,
  'downloadVideo' : ActorMethod<[bigint], undefined>,
  'getAllPhotos' : ActorMethod<[], Array<PhotoMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhotoMetadata' : ActorMethod<[bigint], PhotoMetadata>,
  'getPhotoStorageUsage' : ActorMethod<[], bigint>,
  'getUserLanguagePreference' : ActorMethod<[], Language>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], VideoMetadata>,
  'getVideoStorageUsage' : ActorMethod<[], bigint>,
  'getVideos' : ActorMethod<[], VideosResponse>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserLanguagePreference' : ActorMethod<[Language], undefined>,
  'updateProfilePicture' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'uploadMultiplePhotos' : ActorMethod<[BulkPhotoUploadRequest], Array<bigint>>,
  'uploadMultipleVideos' : ActorMethod<
    [{ 'videos' : Array<VideoUploadRequest> }],
    BulkVideoUploadResponse
  >,
  'uploadPhoto' : ActorMethod<[PhotoUploadRequest], bigint>,
  'uploadVideo' : ActorMethod<[VideoUploadRequest], VideoUploadResponse>,
  'verifyPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];