/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PhotoUploadRequest {
    storageReference: ExternalBlob;
    contentType: string;
    fileSize: bigint;
    filename: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface BulkVideoUploadResponse {
    errors: Array<string>;
    successCount: bigint;
    message: string;
    videoIds: Array<bigint>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PhotoMetadata {
    id: bigint;
    storageReference: ExternalBlob;
    contentType: string;
    owner: Principal;
    fileSize: bigint;
    filename: string;
    uploadDate: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BulkPhotoUploadRequest {
    photos: Array<PhotoUploadRequest>;
}
export interface VideoUploadResponse {
    message: string;
    videoId: bigint;
}
export interface VideoUploadRequest {
    storageReference: ExternalBlob;
    duration?: bigint;
    contentType: string;
    thumbnailReference?: ExternalBlob;
    fileSize: bigint;
    filename: string;
}
export interface VideoMetadata {
    id: bigint;
    storageReference: ExternalBlob;
    duration?: bigint;
    contentType: string;
    owner: Principal;
    thumbnailReference?: ExternalBlob;
    fileSize: bigint;
    filename: string;
    uploadDate: Time;
}
export interface UserProfile {
    pin: string;
    languagePreference: Language;
    name: string;
    profilePicture?: ExternalBlob;
}
export interface VideosResponse {
    message: string;
    videos: Array<VideoMetadata>;
}
export enum Language {
    hindi = "hindi",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changePin(currentPin: string, newPin: string): Promise<void>;
    deletePhoto(photoId: bigint): Promise<void>;
    deleteVideo(videoId: bigint): Promise<{
        message: string;
    }>;
    downloadVideo(_videoId: bigint): Promise<void>;
    getAllPhotos(): Promise<Array<PhotoMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPhotoMetadata(photoId: bigint): Promise<PhotoMetadata>;
    getPhotoStorageUsage(): Promise<bigint>;
    getUserLanguagePreference(): Promise<Language>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideo(videoId: bigint): Promise<VideoMetadata>;
    getVideoStorageUsage(): Promise<bigint>;
    getVideos(): Promise<VideosResponse>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserLanguagePreference(language: Language): Promise<void>;
    updateProfilePicture(pictureReference: ExternalBlob | null): Promise<void>;
    uploadMultiplePhotos(request: BulkPhotoUploadRequest): Promise<Array<bigint>>;
    uploadMultipleVideos(request: {
        videos: Array<VideoUploadRequest>;
    }): Promise<BulkVideoUploadResponse>;
    uploadPhoto(request: PhotoUploadRequest): Promise<bigint>;
    uploadVideo(request: VideoUploadRequest): Promise<VideoUploadResponse>;
    verifyPin(pin: string): Promise<boolean>;
}
import type { BulkPhotoUploadRequest as _BulkPhotoUploadRequest, ExternalBlob as _ExternalBlob, Language as _Language, PhotoMetadata as _PhotoMetadata, PhotoUploadRequest as _PhotoUploadRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoMetadata as _VideoMetadata, VideoUploadRequest as _VideoUploadRequest, VideosResponse as _VideosResponse, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changePin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePin(arg0, arg1);
            return result;
        }
    }
    async deletePhoto(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: bigint): Promise<{
        message: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async downloadVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadVideo(arg0);
            return result;
        }
    }
    async getAllPhotos(): Promise<Array<PhotoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotoMetadata(arg0: bigint): Promise<PhotoMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoMetadata(arg0);
                return from_candid_PhotoMetadata_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoMetadata(arg0);
            return from_candid_PhotoMetadata_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotoStorageUsage(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoStorageUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoStorageUsage();
            return result;
        }
    }
    async getUserLanguagePreference(): Promise<Language> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLanguagePreference();
                return from_candid_Language_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLanguagePreference();
            return from_candid_Language_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: bigint): Promise<VideoMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_VideoMetadata_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_VideoMetadata_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoStorageUsage(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoStorageUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoStorageUsage();
            return result;
        }
    }
    async getVideos(): Promise<VideosResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideos();
                return from_candid_VideosResponse_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideos();
            return from_candid_VideosResponse_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserLanguagePreference(arg0: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserLanguagePreference(to_candid_Language_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserLanguagePreference(to_candid_Language_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfilePicture(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadMultiplePhotos(arg0: BulkPhotoUploadRequest): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMultiplePhotos(await to_candid_BulkPhotoUploadRequest_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMultiplePhotos(await to_candid_BulkPhotoUploadRequest_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadMultipleVideos(arg0: {
        videos: Array<VideoUploadRequest>;
    }): Promise<BulkVideoUploadResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMultipleVideos(await to_candid_record_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMultipleVideos(await to_candid_record_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadPhoto(arg0: PhotoUploadRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(await to_candid_PhotoUploadRequest_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(await to_candid_PhotoUploadRequest_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadVideo(arg0: VideoUploadRequest): Promise<VideoUploadResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(await to_candid_VideoUploadRequest_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(await to_candid_VideoUploadRequest_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPin(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Language_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_PhotoMetadata_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoMetadata): Promise<PhotoMetadata> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoMetadata_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): Promise<VideoMetadata> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_VideosResponse_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideosResponse): Promise<VideosResponse> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    storageReference: _ExternalBlob;
    contentType: string;
    owner: Principal;
    fileSize: bigint;
    filename: string;
    uploadDate: _Time;
}): Promise<{
    id: bigint;
    storageReference: ExternalBlob;
    contentType: string;
    owner: Principal;
    fileSize: bigint;
    filename: string;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        storageReference: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.storageReference),
        contentType: value.contentType,
        owner: value.owner,
        fileSize: value.fileSize,
        filename: value.filename,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pin: string;
    languagePreference: _Language;
    name: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    pin: string;
    languagePreference: Language;
    name: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        pin: value.pin,
        languagePreference: from_candid_Language_n17(_uploadFile, _downloadFile, value.languagePreference),
        name: value.name,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    storageReference: _ExternalBlob;
    duration: [] | [bigint];
    contentType: string;
    owner: Principal;
    thumbnailReference: [] | [_ExternalBlob];
    fileSize: bigint;
    filename: string;
    uploadDate: _Time;
}): Promise<{
    id: bigint;
    storageReference: ExternalBlob;
    duration?: bigint;
    contentType: string;
    owner: Principal;
    thumbnailReference?: ExternalBlob;
    fileSize: bigint;
    filename: string;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        storageReference: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.storageReference),
        duration: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.duration)),
        contentType: value.contentType,
        owner: value.owner,
        thumbnailReference: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.thumbnailReference)),
        fileSize: value.fileSize,
        filename: value.filename,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    videos: Array<_VideoMetadata>;
}): Promise<{
    message: string;
    videos: Array<VideoMetadata>;
}> {
    return {
        message: value.message,
        videos: await from_candid_vec_n26(_uploadFile, _downloadFile, value.videos)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    english: null;
}): Language {
    return "hindi" in value ? Language.hindi : "english" in value ? Language.english : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhotoMetadata>): Promise<Array<PhotoMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PhotoMetadata_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMetadata>): Promise<Array<VideoMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoMetadata_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_BulkPhotoUploadRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkPhotoUploadRequest): Promise<_BulkPhotoUploadRequest> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Language_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function to_candid_PhotoUploadRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoUploadRequest): Promise<_PhotoUploadRequest> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_VideoUploadRequest_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoUploadRequest): Promise<_VideoUploadRequest> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pin: string;
    languagePreference: Language;
    name: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    pin: string;
    languagePreference: _Language;
    name: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        pin: value.pin,
        languagePreference: to_candid_Language_n29(_uploadFile, _downloadFile, value.languagePreference),
        name: value.name,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photos: Array<PhotoUploadRequest>;
}): Promise<{
    photos: Array<_PhotoUploadRequest>;
}> {
    return {
        photos: await to_candid_vec_n35(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storageReference: ExternalBlob;
    contentType: string;
    fileSize: bigint;
    filename: string;
}): Promise<{
    storageReference: _ExternalBlob;
    contentType: string;
    fileSize: bigint;
    filename: string;
}> {
    return {
        storageReference: await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.storageReference),
        contentType: value.contentType,
        fileSize: value.fileSize,
        filename: value.filename
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videos: Array<VideoUploadRequest>;
}): Promise<{
    videos: Array<_VideoUploadRequest>;
}> {
    return {
        videos: await to_candid_vec_n39(_uploadFile, _downloadFile, value.videos)
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storageReference: ExternalBlob;
    duration?: bigint;
    contentType: string;
    thumbnailReference?: ExternalBlob;
    fileSize: bigint;
    filename: string;
}): Promise<{
    storageReference: _ExternalBlob;
    duration: [] | [bigint];
    contentType: string;
    thumbnailReference: [] | [_ExternalBlob];
    fileSize: bigint;
    filename: string;
}> {
    return {
        storageReference: await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.storageReference),
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        contentType: value.contentType,
        thumbnailReference: value.thumbnailReference ? candid_some(await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.thumbnailReference)) : candid_none(),
        fileSize: value.fileSize,
        filename: value.filename
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    hindi: null;
} | {
    english: null;
} {
    return value == Language.hindi ? {
        hindi: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PhotoUploadRequest>): Promise<Array<_PhotoUploadRequest>> {
    return await Promise.all(value.map(async (x)=>await to_candid_PhotoUploadRequest_n36(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VideoUploadRequest>): Promise<Array<_VideoUploadRequest>> {
    return await Promise.all(value.map(async (x)=>await to_candid_VideoUploadRequest_n40(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
